package com.ife_a.compose_online_class_platform_ui.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF0062a2)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_off_gray = Color(0xFFE9E3E9)
val md_theme_highlight = Color(0x400062A2)
val md_theme_light_primaryContainer = Color(0xFFcfe5ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d36)
val md_theme_light_secondary = Color(0xFF526070)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_gray= Color(0xFFD5D5D5)
val md_theme_light_secondaryContainer = Color(0xFFd6e4f7)
val md_theme_light_onSecondaryContainer = Color(0xFF0f1d2a)
val md_theme_light_tertiary = Color(0xFF6a5779)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf2daff)
val md_theme_light_onTertiaryContainer = Color(0xFF241532)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfcff)
val md_theme_light_onBackground = Color(0xFF363B3F)
val md_theme_light_surface = Color(0xFFfdfcff)
val md_theme_light_onSurface = Color(0xFF1a1c1e)
val md_theme_light_surfaceVariant = Color(0xFFdfe3eb)
val md_theme_light_onSurfaceVariant = Color(0xFF42474e)
val md_theme_light_outline = Color(0xFF73777f)
val md_theme_light_inverseOnSurface = Color(0xFFf0f0f3)
val md_theme_light_inverseSurface = Color(0xFF2f3033)

val md_theme_dark_primary = Color(0xFF99cbff)
val md_theme_dark_onPrimary = Color(0xFF003257)
val md_theme_dark_primaryContainer = Color(0xFF00497b)
val md_theme_dark_onPrimaryContainer = Color(0xFFcfe5ff)
val md_theme_dark_secondary = Color(0xFFbac8db)
val md_theme_dark_onSecondary = Color(0xFF243140)
val md_theme_dark_secondaryContainer = Color(0xFF3b4857)
val md_theme_dark_onSecondaryContainer = Color(0xFFd6e4f7)
val md_theme_dark_tertiary = Color(0xFFd5bee6)
val md_theme_dark_onTertiary = Color(0xFF3a2a48)
val md_theme_dark_tertiaryContainer = Color(0xFF514060)
val md_theme_dark_onTertiaryContainer = Color(0xFFf2daff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c1e)
val md_theme_dark_onBackground = Color(0xFFe2e2e6)
val md_theme_dark_surface = Color(0xFF1a1c1e)
val md_theme_dark_onSurface = Color(0xFFe2e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF42474e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c7cf)
val md_theme_dark_outline = Color(0xFF8c9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
val md_theme_dark_inverseSurface = Color(0xFFe2e2e6)

val seed = Color(0xFF278edd)
val error = Color(0xFFba1b1b)